// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTiQUmvoNJZ1PzE15oOY7HYDHRtwyRn3A',
    appId: '1:49018571901:web:bfe5d0283e7e66bb0a3514',
    messagingSenderId: '49018571901',
    projectId: 'monster-cell-7cb16',
    authDomain: 'monster-cell-7cb16.firebaseapp.com',
    storageBucket: 'monster-cell-7cb16.firebasestorage.app',
    measurementId: 'G-F7KYE1C94S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ZaqF1nCo1bujAkPXm8gerNDSe_5XJpI',
    appId: '1:49018571901:android:17d05e0b162234ef0a3514',
    messagingSenderId: '49018571901',
    projectId: 'monster-cell-7cb16',
    storageBucket: 'monster-cell-7cb16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC29Rj5Grh6s9qJEGxU_KdpoMhRTwtUvqk',
    appId: '1:49018571901:ios:bab3fa862dfa427d0a3514',
    messagingSenderId: '49018571901',
    projectId: 'monster-cell-7cb16',
    storageBucket: 'monster-cell-7cb16.firebasestorage.app',
    iosBundleId: 'com.example.monsterBattleGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC29Rj5Grh6s9qJEGxU_KdpoMhRTwtUvqk',
    appId: '1:49018571901:ios:bab3fa862dfa427d0a3514',
    messagingSenderId: '49018571901',
    projectId: 'monster-cell-7cb16',
    storageBucket: 'monster-cell-7cb16.firebasestorage.app',
    iosBundleId: 'com.example.monsterBattleGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTiQUmvoNJZ1PzE15oOY7HYDHRtwyRn3A',
    appId: '1:49018571901:web:55170f7de81eb2a60a3514',
    messagingSenderId: '49018571901',
    projectId: 'monster-cell-7cb16',
    authDomain: 'monster-cell-7cb16.firebaseapp.com',
    storageBucket: 'monster-cell-7cb16.firebasestorage.app',
    measurementId: 'G-HNR5PTZ16P',
  );
}
