name: Build and Release Android APK

on:
  push:
    branches:
      - main # Action berjalan otomatis setiap kali kamu push ke branch main
  workflow_dispatch: # Mengizinkan kamu menjalankan action ini secara manual dari GitHub UI

jobs:
  build_and_release:
    name: Build & Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' # Sangat disarankan Java 17 untuk versi Gradle terbaru

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v1.0.${{ github.run_number }}" # Otomatis buat versi baru
          name: "Release v1.0.${{ github.run_number }}" # Nama release otomatis
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}